### ISSUE TITLE
twitchrec is down ?

### ISSUE THREAD

**Issue by praaly** [StianWiu/TwitchRec#29]
Recording will start when username goes live or starts a rerun  (for all live twitch)

**Comment by StianWiu** [comment]
Correct me if I am wrong but it is not recording even though your streamer is online?

**Comment by praaly** [comment]
Yes, I think it's from your scrapper that checks if the channel is online

**Comment by StianWiu** [comment]
You haven't gotten back to me by email so I am going to close this issue, feel free to open it again if your issue wasn't resolved.

**Comment by ghost** [comment]
Sorry, yes is fixed
Thanks!
